/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFilmRegistryView__factory } from "./IFilmRegistryView__factory";
export { RevenueManager__factory } from "./RevenueManager__factory";
