/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as licenseManagerSol from "./LicenseManager.sol";
export type { licenseManagerSol };
import type * as revenueManagerSol from "./RevenueManager.sol";
export type { revenueManagerSol };
import type * as rightsNftSol from "./RightsNFT.sol";
export type { rightsNftSol };
export type { FilmRegistry } from "./FilmRegistry";
