/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRevenueManager } from "./IRevenueManager";
export type { LicenseManager } from "./LicenseManager";
