/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRevenueManager__factory } from "./IRevenueManager__factory";
export { LicenseManager__factory } from "./LicenseManager__factory";
